---
AWSTemplateFormatVersion: '2010-09-09'

Description: >-
  S3 bucket for Lambda deployment packages

Resources:
  Bucket:
    Type: AWS::S3::Bucket

    # BucketPolicy:
    #  Type: AWS::S3::BucketPolicy
    #  Properties:
    #    Bucket: !Ref BucketName
    #    PolicyDocument:
    #      Version: '2012-10-17'
    #      Statement:
    #        - Effect: Allow
    #          Principal:
    #            Service: lambda.amazonaws.com
    #          Action: 's3:GetBucketAcl'
    #          Resource: !GetAtt Bucket.Arn
    #        - Effect: Allow
    #          Principal:
    #            Service: cloudtrail.amazonaws.com
    #          Action: 's3:PutObject'
    #          Resource: -Join ['', !GetAtt Bucket.Arn, '/AWSLogs/*']
    #          Condition:
    #            StringLike:
    #              's3:x-xml-acl': 'bucket-owner-full-control'

Outputs:
  Bucket:
    Description: Name of bucket
    Value: !Ref Bucket
